Azure/missionlz

src/docs/command-line-deployment.md
Update how the command is used
The issue this PR will close: #_[issue number]_ https://github.com/Azure/missionlz/issues/108
=> Updated usage example in command-line-deployment.md file

.gitignore
Updated the .gitignore to ignore all .tfvars.json files so that we can work with multiple sets of configs locally without those files polluting the repo.
Closes #104 
=> Ignore *.tfvars.json files

.github/workflows/validate-terraform.yml
Use [hashicorp's setup-terraform GitHub Action](https://github.com/hashicorp/setup-terraform) to download Terraform CLI and add it to the agent for the validate-terraform.yml workflow instead of using our dev container.
The issue this PR will close: #103
=> use hashicorp Action in validate-terraform workflow instead of devcontainer

src/docs/getting-started.md
The link I created in the previous pull request had a grey background on the link text that this removes. Also, the wording also had a redundant reference to "or Linux Virtual Machine" that is now removed.
The issue this PR will close: #_[issue number]_
=> removing unnecessary background on link text

src/core/globals.front.json, src/front/main.py, src/scripts/setup_ezdeploy.sh
As noted in #138 , the UI will return 500's when trying to execute terraform because the environment variable `Location` is a reserved key. This change uses `MLZ_LOCATION` instead.
The issue this PR will close: #138
=> use MLZ_LOCATION instead of reserved term Location

.github/workflows/README.md, .github/workflows/apply-and-destroy-terraform.yml, src/build/get_vars.sh, src/build/login_azcli.sh
As mentioned in #136, to support other types of CI technology, this change updates the automation scripts in /build (specifically those to get .tfvars files, an MLZ config file, and to login to az cli) to pass arguments instead of relying on keyvault values mapped to the environment and updates the sample workflow with these new arguments.
The issue this PR will close: #136
=> use arguments for build scripts

src/core/saca-hub/main.tf, src/modules/firewall/main.tf, src/modules/firewall/variables.tf
Toggle "Premium" or "Standard" Azure Firewall SKU given the Terraform azurerm environment setting.
The issue this PR will close: #111 
=> set firewall SKU to Premium where azurerm environments support it

src/scripts/config/mlz_config_create.sh, src/scripts/container-registry/add_auth_scopes.sh, src/scripts/setup_ezdeploy.sh
Updated the commands used to push Docker image to use dynamic endpoints.
Added login to wait for the App creation process to propagate all properties before proceeding
The issue this PR will close: #144 
=> Update Docker push commands and add checks for App properties

src/docs/scca.md
Documentation on how Mission LZ maps to SCCA controls:
https://github.com/Azure/missionlz/blob/6c1112eefa2cc0b3aa299d477abec6ed0f9f5b8a/README.md#product-roadmap
The issue this PR will close: #38
=> SCCA Mapping

src/Dockerfile, src/docs/ui-deployment.md, src/scripts/container-registry/add_auth_scopes.sh, src/scripts/export_docker.sh, src/scripts/setup_ezdeploy.sh
Add export option for docker building
Refactored Docker Build in code order to allow for an exit after a local save
Allow for user to not enter any commands other than docker_strategy=export when exporting
Added sed to dockerfile
Fixed shellcheck recommend on add_auth_scopes.sh
The issue this PR will close:  #169 
=> Docker Export/Load

src/modules/firewall/main.tf, src/modules/firewall/variables.tf
Configure the firewall to never SNAT regardless of the destination IP address, preventing Azure Firewall from routing traffic directly to the internet
The issue this PR will close: #118 
* [x ] Code compiles or validates correctly
* [x ] All tests pass (manual and automated)
* [x ] Relevant issues are linked to this PR
=> Disable SNAT regardless of the destination IP address (Firewall) since forced tunneling is turned on

.devcontainer/Dockerfile, src/Dockerfile
Pins the Azure CLI to version 2.22.0 as that was the last known version that successfully manages KeyVaults in AzureUsGovernment.
The issue this PR will close: #200
=> pin azure cli to 2.22.0

.devcontainer/Dockerfile
Removed the symbolic link creation for pip in the dev container.  The current Ubuntu 20.04 base image already contains this symlink and this code was failing with the error 
``` 
ln: failed to create symbolic link '/usr/bin/pip': File exists
The command '/bin/sh -c apt-get update     && 
apt-get install -y     python3     python3-pip     && 
ln -s /usr/bin/python3 /usr/bin/python     && 
ln -s /usr/bin/pip3 /usr/bin/pip' 
returned a non-zero code: 1
Failed to create container.
```
The issue this PR will close: #207 
=> Remove symbolic link for pip in devcontainer

src/core/saca-hub/main.tf, src/core/saca-hub/saca-hub.front.json, src/core/saca-hub/saca-hub.orig.tfvars.json, src/core/saca-hub/saca-hub.tfvars.sample, src/core/saca-hub/variables.tf, src/modules/bastion/main.tf, src/modules/bastion/variables.tf, src/scripts/clean.sh
Adds an Azure Bastion Host module that can be added to any virtual network given a valid subnet larger than /27.
To know this is working deploy an instance of MLZ and inspect the SACA Hub resource group. With the supplied defaults you should see a `mlzDemoBastionHost` resource and its accompanying public IP address `mlzDemoBastionHostPip` reside in a `AzureBastionSubnet` of `10.0.100.128/27`.
The issue this PR will close: #186 
=> add a Bastion Host module

src/scripts/clean.sh, src/scripts/config/append_prereq_endpoints.sh, src/scripts/deploy.sh, src/scripts/deploy_ui.sh
Due to the differences in clouds, we cannot guarantee each service will be available that MLZ requires.
For instance, today, in one of the clouds, `az cloud show --query suffixes.acrLoginServerEndpoint` returns no results. So I won't be able to deploy the UI to a container instance.
This change allows for an empty result to be written to a generated .mlzconfig file, and at least for the UI, catches empty values and throws an error and exits if that's the case.
The issue this PR will close: #235
=> allow for empty az cloud show results when building .mlzconfig files

.devcontainer/README.md
Simply added a reference to the project getting started as step 1
The issue this PR will close: #212
=> Update README.md (added reference to getting started docs)

src/docs/getting-started.md
The quickstart scripts require a user with the owner role (e.g. to create the service account and grant it permissions on the subscription)
Added the pre-req of a user with "owner" on the subscription (this is required for the quickstart
The issue this PR will close: #212
=> Added "owner" requirement to Mission LZ pre-reqs

src/docs/command-line-deployment.md
Updated pre-reqs for local BASH
- Removed the "additional" pre-req of an "Owner" account because this is not an additional requirement
- Updated the Az CLI command to check the version ("az cli -v" is not proper syntax)
The issue this PR will close: #212
=> Updated stated pre-reqs for local BASH

src/scripts/config/append_prereq_endpoints.sh
Today, users in air-gapped clouds have issues initializing terraform backends when using the full ARM Metadata Host Service Endpoint URI (e.g. "https://management.azure.com/") and instead require just the host name (e.g. "management.azure.com")
This change, when using the `deploy.sh` quickstart, removes the URI components from the result of `az cloud show --query endpoints.resourceManager` when the .mlzconfig file is generated so that just the hostname value is passed as a `metadata_host` argument during terraform backend initialization. See #241 for more information.
Before, a .mlzconfig generated from `deploy.sh` used to generate a key value pair like this:
```plaintext
mlz_metadatahost=https://management.azure.com/
```
Now, it should generate a value like this:
```plaintext …
```
=> remove URI components from metadata host service endpoint when generating .mlzconfig

src/core/saca-hub/saca-hub.front.json, src/core/saca-hub/variables.tf, src/core/tier-0/tier-0.front.json, src/core/tier-1/tier-1.front.json, src/core/tier-2/tier-2.front.json, src/core/tier-3/tier-3.front.json
Removes the word demo from default resource names.
The issue this PR will close: #249 
=> Remove the word demo from default resource names

.devcontainer/Dockerfile, src/Dockerfile, src/scripts/config/mlz_config_create.sh
Fix an issue where checking for unique SP was not working properly.
Added support for AZ CLI 2.25.0 and it should support newer versions as well. I found a better way to get and use the AppID instead of display name.
NA
=> Compatibility support for AZ CLI v2.25.0

src/docs/getting-started.md
The getting-started docs jumped from configuring your environment to adding workloads, missing the step to deploy the hub and spoke. This change adds a link to that documentation.
The issue this PR will close: n/a
~~Code compiles or validates correctly~~
~~BASH scripts have been validated using `shellcheck`~~
~~All tests pass (manual and automated)~~
~~Relevant issues are linked to this PR~~
=> add command line deployment to getting-started.md

.devcontainer/devcontainer.json
Using "terminal.integrated.profiles.linux" to define the bash profile, and "terminal.integrated.defaultProfile.linux" to set it as default.
The issue this PR will close: #272 
=> update devcontainer.json as "terminal.integrated.shell.linux" is deprecated

src/docs/getting-started.md, src/scripts/clean.sh
I noticed the clean script does not remove these:
/src/terraform/mlz/config.vars
/src/terraform/mlz/.terraform.lock.hcl
/src/terraform/mlz/.terraform
NA
* [ x] Code compiles or validates correctly
* [ x] BASH scripts have been validated using `shellcheck`
* [ x] All tests pass (manual and automated)
* [x ] The documentation is updated to cover any new or changed features
* [x ] Markdown files have been linted using the recommended linter. (See `.vscode/extensions.json`.)
* [x ] Relevant issues are linked to this PR
=> Removing some extra auto-generated configurations and terraform related files and folders

src/docs/command-line-deployment.md, src/scripts/deploy.sh, src/scripts/terraform/create_tfvars_from_config.sh, src/terraform/mlz/main.tf, src/terraform/mlz/minimum.tfvars.sample, src/terraform/mlz/mlz.tfvars.sample, src/terraform/mlz/variables.tf
Adds an Azure Sentinel deployment to the Tier 1 Log Analytics Workspace by default.
Users can opt-out of this in two ways:
1. when invoking Terraform manually, supply a Terraform variable `create_sentinel = false`
2. or, when using the `deploy.sh` script, passing the `--no-sentinel` flag.
To demo this, deploy as you usually would: `src/scripts/deploy.sh -s ${my_sub_id}`
To deploy without Azure Sentinel: `src/scripts/deploy.sh -s ${my_sub_id} --no-sentinel`
The issue this PR will close: #256
=> optionally deploy Azure Sentinel solution into Tier 1 Log Analytics Workspace

.gitattributes
Update the .gitattributes in the repo to treat all BASH scripts with LF endings so that wherever someone clones the repository, when the .devcontainer interacts with these files, they'll be executable.
The issue this PR will close: #291 
=> update .gitattributes to use LF endings for *.sh

src/terraform/modules/jumpbox/main.tf
Adds a Linux password to the jumpbox keyvault that meets these constraints:
```plaintext
The supplied password must be between 6-72 characters long and must satisfy at least 3 of password complexity requirements:
- contains an uppercase character
- contains a lowercase character
- contains a numeric digit
- contains a special character
- control characters are not allowed
```
The issue this PR will close: #289
=> add Linux jumpbox password constraints

src/scripts/config/create_required_resources.sh, src/scripts/terraform/init_terraform.sh
Fixes a bug where deploy.sh will fail because it will always look in the hub subscription for the Terraform state storage account:
```bash
src/scripts/deploy.sh -s {config_sub_id} \
-u {hub_sub_id} \
-0 {t0_sub_id} \
-1 {t1_sub_id} \
-2 {t2_sub_id} \
-3 {t3_sub_id}
```
Would result in a Terraform initialization that specified the `hub_sub_id` as the place to search for Terraform state regardless of where it was actually deployed.
The issue this PR will close: #302 
=> Fix a bug where config resources were always created in the Hub subscription

CONTRIBUTING.md
The issue this PR will close: #233
* ~~[ ] Code compiles or validates correctly~~
* ~~[ ] BASH scripts have been validated using `shellcheck`~~
* ~~[ ] All tests pass (manual and automated)~~
=> Updated contribution process

.devcontainer/Dockerfile, src/terraform/mlz/main.tf, src/terraform/tier3/main.tf
* Update Terraform to version 1.0.3
* Update azurerm to version 2.69.0
* Update az cli to version 2.26.1
* Update time terraform provider to version 0.7.2
* Update tflint to version 0.30.0
* Update azurerm tflint rules to version 0.11.0
Pinned terraform version to 1.0.3 in main.tf files
This configuration was tested in Azure Commercial and Government (usgovvirginia)
NA
=> Update Terraform to version 1.0.3

src/terraform/mlz/main.tf, src/terraform/tier3/main.tf
Changed the required Terraform version number to 1.0.3 in main.tf. (1.0.4 is still built in the dev container.)
The issue this PR will close: #335
=> update terraform required version

.gitignore, src/terraform/mlz/variables.tf
* Fixed some warning notifications due to missing types.
* Added some default values to easy execute terraform apply for quick testing.
* Added sensitive flags to some variables.
* Updated some descriptions for better documentation.
* Added generated plans and crashes to .gitignore so these are not pushed by mistake.
NA
=> Updating mlz variables file

.github/CODEOWNERS, CONTRIBUTING.md
Added `CODEOWNERS` file to define which people are the default set of reviewers for PRs.
=> Add CODEOWNERS file

src/docs/terraform/deployment.md
This change introduces documentation on the minimum required to provision resources describes at `src/terraform/mlz` with Terraform into AzureCloud and AzureUsGovernment without any help from anything at `src/scripts`.
NOTE: following the docs verbatim in the `/bicep` branch in its current state will not work as we're still referencing an `azurerm` backend that is not created and referencing Service Principal credential variables that are not created. Will constantly make updates to this doc as "truth" changes for required parameters, etc.
The issue this PR will close: #354 
~~BASH scripts have been validated using `shellcheck`~~
~~All tests pass (manual and automated)~~
=> Provide docs on deployment using native terraform CLI commands

src/bicep/modules/resourceGroup.bicep
Changed Providers to ensure mlz code runs on as many clouds as possible
The issue this PR will close: #347
=> Set resource provider API versions

src/mlz.config.sample, src/terraform/mlz/main.tf, src/terraform/mlz/minimum.tfvars.sample, src/terraform/mlz/mlz.tfvars.sample, src/terraform/mlz/variables.tf, src/terraform/tier3/main.tf, src/terraform/tier3/minimum.tfvars.sample, src/terraform/tier3/tier3.tfvars.sample, src/terraform/tier3/variables.tf
Removed all variables instances in Terraform Template of: mlz_clientid, mlz_clientsecret, mlz_tenantid
The issue this PR will close: #378 
=> Remove Client/Client Secret/Tenant Vars from Terraform Templates

src/bicep/bicepconfig.json
Toggles the verbosity of the Bicep linter to report only errors. Mostly useful to omit the `Info Bicep Linter Configuration: Custom bicepconfig.json file found` on each module that uses the linter:
The first command is before `verbose: true`, the second command is after `verbose: false`:
The issue this PR will close: #360
~~[ ] Code compiles or validates correctly~~
~~[ ] BASH scripts have been validated using `shellcheck`~~
~~[ ] All tests pass (manual and automated)~~
~~[ ] The documentation is updated to cover any new or changed features~~
~~[ ] Markdown files have been linted using the recommended linter. (See `.vscode/extensions.json`.)~~
~~[ ] Relevant issues are linked to this PR~~
=> report only errors in Bicep lint output

src/bicep/README.md, src/bicep/mlz.bicep, src/bicep/modules/policies/CMMC-policyAssignmentParameters.json, src/bicep/modules/policies/IL5-policyAssignmentParameters.json, src/bicep/modules/policies/NIST-policyAssignmentParameters.json, src/bicep/modules/policyAssignment.bicep
Add parameter based deployment for Policy initiative deployment of NIST/CMMC/IL5 as needed. 
The issue this PR will close: #387 
=> optionally deploy built-in Policy Initiatives for NIST 800-53, CMMC Level 3, or DOD IL5

src/build/apply_tf.sh, src/build/destroy_tf.sh
Changed the value of max_attempts to 1 so that it will fail fast as opposed to looping 5 times, leaving the retry logic in place however to allow for future debug attempts. 
The issue this PR will close: #362 
=> fail fast on deployments by decrementing max_attempts to 1

src/bicep/mlz.bicep, src/bicep/modules/centralLogging.bicep
setting the diagnostic setting name from the root module instead of at the component module and the value to be explicitly what is being logged where instead of using the generated random name
=> diagnostic name with log analytics workspace name

src/bicep/README.md, src/bicep/examples/remoteAccess/main.bicep, src/bicep/examples/remoteAccess/main.json, src/bicep/mlz.bicep, src/bicep/mlz.json, src/bicep/modules/linuxVirtualMachine.bicep, src/bicep/modules/remoteAccess.bicep, src/bicep/modules/windowsVirtualMachine.bicep
This change introduces a Windows Virtual Machine into the `remoteAccess` module, giving a user a remote desktop interface inside the network by specifying `deployRemoteAccess=true` and a value for `linuxVmAdminPasswordOrKey` and `windowsVmAdminPassword` at deployment time.
To demo this (it's easiest to use the .devcontainer to generate a password with `openssl`) try:
```plaintext
my_password=$(openssl rand -base64 14)
az deployment sub create \
--name "myRemoteAccessDeployment" \
--location "eastus" \
--template-file "src/bicep/mlz.bicep" \
--parameters deployRemoteAccess="true" \
--parameters linuxVmAdminPasswordOrKey="$my_password" \
--parameters windowsVmAdminPassword="$my_password"
```
If a user attempts to set `deployRemoteAccess=true` but forgets to supply a password like this: …
=> include a Windows virtual machine for jumpbox access

.github/workflows/validate-terraform.yml, src/build/check_tf_format.sh, src/build/validate_tf.sh, src/terraform/modules/firewall/variables.tf
This changes the terraform validation triggered on Pull Requests to only occur with modifications to things at `/src/terraform/**` and updates the validation and formatting checks to accept N number of directories.
The issue this PR will close #407
~~The documentation is updated to cover any new or changed features~~
~~Markdown files have been linted using the recommended linter. (See `.vscode/extensions.json`.)~~
=> update Terraform CI validation and CI trigger

src/bicep/mlz.bicep, src/bicep/mlz.json
Added a `deploymentType` tag to differentiate the method of implementation
The issue this PR will close: #85 
=> Adding deploymentType tag to resources

src/bicep/examples/inheritTags/README.md, src/bicep/examples/inheritTags/inherit.bicep
This push adds an example with instructions and pointers to documentation for how to attach and manage a tag inheritance policy.  It includes a bicep file with the assignment resource, as well as a readme describe how to make use of the template.
The issue this PR will close: #342 
=> Tested policy for adding a tag inherit policy

docs/policies.md, src/bicep/README.md, src/bicep/examples/newWorkload/README.md, src/bicep/examples/remoteAccess/README.md, src/bicep/mlz.bicep, src/bicep/mlz.json, src/bicep/modules/hubNetworkPeerings.bicep, src/bicep/modules/logAnalyticsWorkspace.bicep, src/bicep/modules/policyAssignment.bicep, src/bicep/modules/resourceGroup.bicep, src/bicep/modules/spokeNetworkPeering.bicep
This change creates spokes and their dependencies in the same way to reduce the likelihood of introducing changes that causes spokes to differ.
First, it creates a `mlz.bicep` array called `spokes` that is composed of user-defined and defaulted parameters:
https://github.com/Azure/missionlz/blob/d95dc7a43a32260fe6532fab1b313c2f7cff764e/src/bicep/mlz.bicep#L557-L561
Then, it uses [Bicep's loop syntax](https://docs.microsoft.com/en-us/azure/azure-resource-manager/bicep/loops) to create modules for those items in the `spokes` array:
https://github.com/Azure/missionlz/blob/d95dc7a43a32260fe6532fab1b313c2f7cff764e/src/bicep/mlz.bicep#L17-L25
This change also adds documentation on how to retrieve deployed resources programmatically:
https://github.com/Azure/missionlz/blob/d95dc7a43a32260fe6532fa …
=> use Bicep loop syntax to create spoke resources the same way

src/bicep/examples/newWorkload/newWorkload.bicep, src/bicep/examples/newWorkload/newWorkload.json, src/bicep/mlz.bicep, src/bicep/mlz.json, src/bicep/modules/spokeNetworkPeering.bicep
Regenerated the ARM template from the Bicep template. Also fixed an issue in which the `spokeType` parameter was not being supplied for the `workloadVirtualNetworkPeerings` module.
The issue this PR will close: #501
=> Regenerated new workload ARM template and added missing module param

src/bicep/mlz.bicep, src/bicep/mlz.json, src/bicep/modules/logAnalyticsDiagnosticLogging.bicep
Deploying to clouds other than pub and gov may cause issues adding diagnostic settings to the workspace (essentially monitoring the workspace itself) since the Audit logs are not supported in all clouds. The PR added the environment check and removed the boolean parameter for deploying this diagnostic setting.
The issue this PR will close: #519 
=> Check cloud before collecting audit logs

src/bicep/README.md
Updated documentation to reflect the username default for the Jumpbox and bastion VM.
The issue this PR will close: #449 
=> updating documentation with username

src/bicep/mlz.json, src/bicep/modules/roleAssignment.bicep
Updated the expected values in roleAssignment.bicep
The issue this PR will close: #486
=> Updating roleAssignment.bicep expected values

src/bicep/mlz.json, src/bicep/modules/privateLink.bicep
During testing it was discovered that longer than normal prefix naming could cause private link scoping (which was set to 16 characters) to truncate the LAWS name down to ending with a hyphen which in turn broke creating the private link scope.
The issue this PR will close: #527 
=> modified private link naming variables

src/terraform/README.md
Added note to the TF readme regarding Azure Cloud Shell.
The issue this PR will close: #540
* ~~[ ] Manual tests have passed`~~
=> Update the Terraform deployment README.md to describe benefits and risks of using Azure Cloud Shell

src/bicep/mlz.bicep, src/bicep/mlz.json
Removed the default values of Hub NSG rules
The issue this PR will close: #443 
=> Remove default NSG rules for 22 and 3389 from Bicep deployment

src/bicep/README.md
Updated the bicep prerequisites
The issue this PR will close: #545
* ~~[ ] Manual tests have passed~~
=> Updated prerequisites in the bicep readme

.azure-devops/nightlybuild/mlz-bicep-azurecloud-pipelines.yml, .azure-devops/nightlybuild/mlz-bicep-azuregov-pipelines.yml, .azure-devops/prbuild/mlz-pr-bicep-azurecloud-pipelines.yml, .azure-devops/prbuild/mlz-pr-bicep-azuregov-pipelines.yml, README.md, src/bicep/README.md, src/bicep/mlz.bicep, src/bicep/mlz.json
This change:
- makes `resourcePrefix` a mandatory parameter 
- removes `deployment().name` as a seed for resource names and uniqueness
- uses `resourcePrefix` for resource names
- uses `resourcePrefix` + `utcNow()` to generates uniqueness
- updates Azure DevOps pipelines to ensure a `resourcePrefix` parameter is supplied to deployment commands
- updates documentation to inform users that this parameter is now mandatory and used for naming
The issue this PR will close: #552 
=> Enforce a mandatory resourcePrefix parameter

src/bicep/mlz.bicep, src/bicep/mlz.json, src/bicep/modules/firewall.bicep, src/bicep/modules/hubNetwork.bicep
Enables IDPS by default and provides a parameter for setting the IDPS value. 
Also added validation to the `threadIntelMode` parameter. Both parameters use the same list of allowed values: Alert, Deny, Off.
The issue this PR will close: #539 
* ~~[] The documentation is updated to cover any new or changed features~~
=> Enable intrusion detection (IDPS) by default

src/bicep/README.md
Update the Bicep `README.md` to include cleanup instructions, especially for deleting subscription-level diagnostic settings.
The issue this PR will close: #423 
=> Add Bicep cleanup instructions for diagnostic settings

src/bicep/mlz.bicep, src/bicep/mlz.json
Performing source hygiene on `mlz.bicep` by moving parameters to the beginning of the file and adds description for each parameter.
The issue this PR will close: #529 
=> relocate Bicep parameters and add descriptions to mlz.bicep

docs/management-groups.md, src/bicep/README.md, src/bicep/mlz.bicep
Updated the docs for management groups
The issue this PR will close: none
=> Updated management group docs

.azure-devops/nightlybuild/mlz-bicep-azurecloud-pipelines.yml, .azure-devops/nightlybuild/mlz-bicep-azuregov-pipelines.yml, .devcontainer/devcontainer.json
The Tier 3/New Workload deployment requires the `deploymentVariables.json` file to be present at `src/bicep/examples` and it has since been removed from the repo.
This change builds that necessary file.
This PR adds to #569 
=> Generate deploymentVariables.json in pipelines

.gitignore, src/bicep/examples/newWorkload/README.md
Updates to the new workload readme to fix minor typos and inaccuracies.
Changed .gitignore to include `deploymentVariables.json` from any path.
The issue this PR will close: #576
=> Updates to the new workload readme

src/bicep/examples/remoteAccess/main.bicep, src/bicep/examples/remoteAccess/main.json, src/bicep/form/mlz.portal.json, src/bicep/mlz.bicep, src/bicep/mlz.json, src/bicep/modules/linuxVirtualMachine.bicep, src/bicep/modules/remoteAccess.bicep, src/bicep/modules/windowsVirtualMachine.bicep
This change:
- updates the password requirements for all remote access modules to be just 12 characters long
- removes the custom Windows password form validation
To demo this (this button below launches the Custom Portal Blade experience from this branch, `glenn/removeWindowsFormPasswordCustomValidation`, the READMEs in this branch are linked to their eventual destination, `/main` after these changes are merged):
[![Deploy to Azure](https://aka.ms/deploytoazurebutton)](https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2Fmissionlz%2Fglenn%2FremoveWindowsFormPasswordCustomValidation%2Fsrc%2Fbicep%2Fmlz.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2Fmissionlz%2Fglenn%2FremoveWindow …
=> Update password requirements to require only 12 characters

src/bicep/modules/linuxVirtualMachine.bicep, src/bicep/modules/windowsVirtualMachine.bicep
Removed unnecessary `dependsOn` items to resolve Bicep warnings on compile and deploy.
The issue this PR will close: #586
=> Fix warnings for unnecessary Bicep dependsOn statements

src/bicep/examples/sentinel/README.md
Clarified the purpose of the Terraform template that deploys Azure Sentinel.
The issue this PR will close: #573 
=> Sentinel example readme clarification

src/bicep/examples/appServicePlan/appService.bicep, src/bicep/examples/appServicePlan/modules/appServicePlan.bicep, src/bicep/examples/containerRegistry/contRegistry.bicep, src/bicep/examples/containerRegistry/modules/containerRegistry.bicep, src/bicep/examples/inheritTags/README.md, src/bicep/examples/keyVault/azureKeyVault.bicep, src/bicep/examples/keyVault/modules/keyVault.bicep, src/bicep/examples/newWorkload/newWorkload.bicep, src/bicep/examples/remoteAccess/main.bicep, src/bicep/examples/remoteAccess/main.json, src/bicep/mlz.json, src/bicep/modules/resourceGroup.bicep, src/bicep/modules/spokeNetwork.bicep, src/bicep/modules/virtualNetwork.bicep
Updated Bicep examples to add the same tags as the base MLZ Bicep deployment. Users can supply an optional parameter to add tags, and the example will union those tags with the standard MLZ tags. 
I considered adding a new module for calculating the tags, like this:
```Bicep
targetScope = 'subscription'
param tags object = {}
var defaultTags = {
'DeploymentType': 'MissionLandingZoneARM'
}
var calculatedTags = union(tags, defaultTags)
output tags object = calculatedTags
```
Which would be called from another template like this: 
```Bicep
param tags object = {}
module calculatedTags '../../modules/calculateTags.bicep' = {
name: 'calculatedTags'
params: {
tags: tags
}
}
```
The advantage would be that it's a single place to manage the default tags. However, I didn't use it because the amount …
=> Add default tags to Bicep examples

src/bicep/form/mlz.portal.json
Changed from `Microsoft.Compute.CredentialsCombo` to `Microsoft.Common.PasswordBox` because the Azure Portal no longer supports the `CredentialsCombo` control.
> NOTE: For now the ability to enter an SSH key has been removed because `PasswordBox` does not support that feature. We will update with an additional PR to add it back.
The issue this PR will close: #615 
=> Remove `Microsoft.Compute.CredentialsCombo` from portal user interface

src/bicep/form/mlz.portal.json
A recent change #622 introduces a supernet to allow cross-spoke traffic.
This change updates the Portal UI to include an input for this value. It is set to the default in the template.
To demo this: https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2Fmissionlz%2Fmain%2Fsrc%2Fbicep%2Fmlz.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2Fmissionlz%2Fglenn%2FaddSupernetToUi%2Fsrc%2Fbicep%2Fform%2Fmlz.portal.json
The issue this PR will close: #608 
=> Add supernet address prefix parameter input to Portal UI

src/terraform/mlz/main.tf
Fixed a bug in which the `coalesce` statement to determine which subscription to deploy tier 2 into has the wrong parameter order.
The issue this PR will close: #637 
=> Fix for Terraform issue in which the tier 2 subscription parameter is ignored

CONTRIBUTING.md
This PR updates the CONTRIBUTING.md guide to add instructions for handling broken nightly builds.
The issue this PR will close: N/A
=> Process for handling a broken build

docs/deployment-guide-bicep.md
Adds instructions for cleaning up Azure Security Center/Defender configuration applied when the `deployASC=true` parameter is used to deploy MLZ.
> NOTE: The guidance still refers to "Azure Security Center" in order to be consistent with other docs and code in the repo. Another backlog item will cover changing the name to Azure Defender for Cloud.
The issue this PR will close: #570 
=> Add instructions for ASC/Defender cleanup

.azure-devops/nightlybuild/templates/az-deployment.yml
Due to changes made in the restructure, a path was missed in the nightly build pipeline causing breakage.   This PR changes the directory from 'examples' to 'add-ons'
=> Change examples to add-ons

.azure-devops/nightlybuild/templates/az-deployment.yml
Post re-structure some directory changes were missed.  deploymentVariables.json was being written to the wrong location, this repairs the location to the add-ons/ folder so that the T3 nightly build can pick it up. 
=> Fix deploymentVariables.json Nightly Build output location

.azure-devops/nightlybuild/templates/az-deployment.yml, src/terraform/mlz/main.tf, src/terraform/tier3/main.tf
There appears to be a problem with parentheses in count expressions, if they are present in a single expression they return the wrong evaluation in the expression.   This removes those parens so that the expression can process correctly. 
=> Remove Parentheses from tier count expression to enable single tier deployment. 

src/bicep/core/hub-network.bicep, src/bicep/core/spoke-network.bicep, src/bicep/mlz.bicep, src/bicep/modules/private-dns.bicep, src/bicep/modules/private-link.bicep
Moved the AMPLS and its Private Endpoint to the Operations tier, so that it sits together with the Log Analytics Workspace. This includes the following changes:
1. Moved the Private DNS zones creation out of the private-link module and into its own module, so that the zones still get created in the Hub.
2. Added a parameter for the VNET Subnet `PrivateEndpointNetworkPolicies` setting in the spoke module, so that the Operations VNET subnet get created with that setting disabled.
3. Moved the Private DNS zones and the AMPLS creation out of the hub module and into the main template, so that they can be deployed to different tiers.
The issue this PR will close: #738
=> Move AMPLS to Operations Tier

README.md
Updated main README.md wiki to document the option to deploy Azure Firewall Standard SKU.
The issue this PR will close: #736 
=> Standard Firewall SKU update

src/bicep/modules/private-link.bicep
The current method for generating `uniqueData` for use in naming resources prevents idempotent deployment because an attempt to create a new AMPLS resource results in a conflict with the previous one. This additionally leads to multiple private endpoints getting created, which could eventually exhaust IP space in the subnet over time if deployed enough times.
I propose that if this is generated using the `uniqueString` Bicep function instead, the random string will be generated in a repeatable manner, provided future deployments are both to the same subscription, and with the same deployment name. Manual testing in an Azure Gov subscription seems good as far as I can tell.
Relevant change is to L22. The remainder are corrections to whitespace by the Bicep plugin in VS Code.
The issue this …
=> Generate uniqueData for Private Link resources in an idempotent manner

src/bicep/examples/iaas-dns-forwarders/README.md, src/bicep/examples/iaas-dns-forwarders/forwarderVm.bicep
Fixed deployment with `extensionsFilesContainerUri` defaulting to public Repo and added more documentation
The issue this PR will close: #752 
=> Fix IaaS DNS forwarders deployment with default extensions uri + more documentation

src/bicep/mlz.bicep, src/bicep/modules/defender.bicep, src/bicep/modules/log-analytics-diagnostic-logging.bicep, src/bicep/modules/policy-assignment.bicep
Syntax changes to address deploy-time warnings.
`use-resource-id-functions` - fixed by referencing the built-in policy defs using tenantResourceId() as described here: https://docs.microsoft.com/en-us/azure/azure-resource-manager/bicep/bicep-functions-resource#tenantresourceid
`prefer-unquoted-property-names` - removed single quotes from keys in the `defaultTags` variable in `mlz.bicep`
`no-unused-existing-resources` - fixed by removing unused `securityContacts` resource from `log-analytics-diagnostic-logging.bicep`
`use-stable-resource-identifiers` - This warning was fixed as a result of prior work done in PR #748
Remaining changes are VSCode formatting artifacts, which I can revert if necessary/desired.
The issue this PR will close: #743
Please make sure you've completed the relevant …
=> Fixing Bicep deploy-time warnings

src/bicep/mlz.bicep, src/bicep/mlz.json
Previously the hub DNS deployment was happening at the same time as remote access deployment. This would create a conflict since the hub DNS deployment would update the VNET the remote access VMs were trying to use for their NICs.  Adding a dependency on the remote access deployment for the hub DNS deployment has resolved the issue.
=> Fixed dependency for remote access

src/bicep/form/mlz.portal.json, src/bicep/mlz.bicep, src/bicep/mlz.json, src/bicep/modules/private-dns.bicep, src/bicep/modules/virtual-network-link.bicep
PR resolves the linked feature request. The code included some other enhancements:
- Virtual Network Links for the Private DNS Zones are now added to the identity VNET when those resources are deployed. If the identity resources are not deployed, links are only created on the hub VNET. In both scenarios, the hub VNET is linked so the MLZ resources continue to work until the DC or Entra Domain Services is established.
- Refactored the "private-dns.bicep" file to remove repetitive code
=> Updates to allow optional identity resources

docs/deployment-guide-bicep.md, src/bicep/README.md, src/bicep/core/hub-network.bicep, src/bicep/core/spoke-network.bicep, src/bicep/form/mlz.portal.json, src/bicep/mlz.bicep, src/bicep/mlz.json, src/bicep/modules/firewall.bicep, src/bicep/modules/virtual-network.bicep
Added optional SKUs for Azure Firewall parameters 
Updated UI definition to expose a dropdown for the selectable SKUs
Add notes that let the user knows if they are not selecting Premium, the environment is not SCCA compliant
Updated firewall deployment to optionally deploy dnsSettings based on SKU
Updated readme files 
Tested and verified deployment 
The issue this PR will close: #794 
=> Add Firewall Option for SKU #794

src/bicep/add-ons/azureVirtualDesktop/README.md
Added the PowerShell code to the README.md file to create a template spec deployment option.
=> Added template spec option

src/bicep/data/locations.json
Locations were added that were about to come online but not GA yet and therefore were missing geo codes for recovery services.  Removed the locations for now and will be added back when they go GA.
=> Removed locations missing geo codes

src/bicep/add-ons/azureVirtualDesktop/uiDefinition.json, src/bicep/form/mlz.portal.json
Added a warning about the firewall SKU for MLZ:
Updated the labels and tool tips for the assignment and custom friendly names sections for AVD.
=> UI Enhancements for MLZ & AVD

src/bicep/add-ons/Imaging/modules/automationAccount.bicep, src/bicep/add-ons/Imaging/modules/buildAutomation.bicep, src/bicep/add-ons/Imaging/modules/customizations.bicep, src/bicep/add-ons/Imaging/modules/imageBuild.bicep, src/bicep/add-ons/Imaging/modules/microsoftUpdates.bicep, src/bicep/add-ons/Imaging/solution.bicep, src/bicep/add-ons/Imaging/uiDefinition.json
Changed custom software download to webclient download to improve performance and prevent timeouts. Found that anything over 10GB downloads with Invoke-WebRequest timed out with the runCommand timeout of 90 minutes. Same download took less than 10 mins with webclient.
Added Microsoft Updates capability to image build allowing Microsoft Update, Windows Update, and WSUS options.
When building my branch, bicep immediately reported issues with the Tier3 deployment which I did not modify. Please investigate!
The issue this PR will close: #[issue number]
* [] Manual tests have passed
=> added webclient and updates

src/bicep/add-ons/tier3/New-AzureTier3TemplateSpec.ps1, src/bicep/add-ons/tier3/README.md, src/bicep/add-ons/tier3/solution.json, src/bicep/add-ons/tier3/uiDefinition.json
Updated and added Tier 3 UI for workload environment
Updated Readme.md to include blue button deployments for commercial and MAG
The issue this PR will close: #843
Tested
=> 843 tier 3 add on create UI definition with blue button deployments

src/bicep/add-ons/azureVirtualDesktop/uiDefinition.json
- Updated VM sizes for ArcGIS deployment on AVD based on ESRI recommendations
- Updated the default AVD agent name to match the latest version name
Issues are linked.
=> AVD Updates: GPU VM sizes & agent name

src/bicep/add-ons/azure-virtual-desktop/uiDefinition.json
Removed condition for friendly names so the ArcGIS profile can create custom friendly names for the workspace and the desktop app.
The issue this PR will close: #1042 
=> Removed condition for friendly names

src/bicep/add-ons/azure-virtual-desktop/modules/sessionHosts/virtualMachines.bicep, src/bicep/add-ons/azure-virtual-desktop/solution.json
The PG updated the APIs that blocked the old way of grabbing the registration token. This PR includes the fix using the new list function in ARM.
The issue this PR will close: #1051
=> Fixed registration token

src/bicep/add-ons/azure-virtual-desktop/modules/management/diskAccess.bicep, src/bicep/add-ons/azure-virtual-desktop/modules/management/management.bicep, src/bicep/add-ons/azure-virtual-desktop/solution.json
Added the DNS zone group to the Disk Access deployment to ensure the private IP is added to the private DNS zone.
The issue this PR will close: #1170 
Test Deployment Confirmation
=> AVD Add-On: Added missing DNS Zone Group to Disk Access deployment
