Azure/missionlz

src/docs/getting-started.md

Simplifying the pre-reqs and setup by including the link
Doc change only. Simply linked to the Docs@MSFT article: 
Windows Subsystem for Linux Installation Guide for Windows 10
https://docs.microsoft.com/en-us/windows/wsl/install-win10
The issue this PR will close: #_[issue number]_

Linking to Win10 WSL install steps (on Docs@MSFT)

---

src/docs/command-line-deployment.md

Update command-line-deployment.md" to run apply for saca_hub before any tier run
https://github.com/Azure/missionlz/issues/123

Updated doc to include saca-hub apply

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/enhancement.md
.github/ISSUE_TEMPLATE/question.md

- Added labels
- Changed "feature request" to "enhancement"

Update issue templates

---

src/terraform/mlz/main.tf

Change jumpbox-subnet firewall from public to private IP
Change jumpbox-subnet firewall from public to private IP
#287 

Fix jumpbox-subnet firewall IP

---

SUPPORT.md

Updated support policy document
The issue this PR will close: #297
* ~~[ ] Code compiles or validates correctly~~
* ~~[ ] BASH scripts have been validated using `shellcheck`~~
* ~~[ ] All tests pass (manual and automated)~~
* ~~[ ] Relevant issues are linked to this PR~~

Added Microsoft CSS support information

---

src/docs/scca.md

The issue this PR will close: #307
* ~~[ ] Code compiles or validates correctly~~
* ~~[ ] BASH scripts have been validated using `shellcheck`~~
* ~~[ ] All tests pass (manual and automated)~~
* ~~[ ] Relevant issues are linked to this PR~~

Fixed SCCA FRD link

---

src/docs/getting-started.md

_Fixing typo in getting-started_
The issue this PR will close: #317 

Fixing typo in getting-started

---

src/terraform/mlz/main.tf

Added the provider attribute tp the laws_sentinel resource
The issue this PR will close: #325 

Set missing provider on Sentinel LAWS

---

.devcontainer/Dockerfile
src/terraform/mlz/main.tf
src/terraform/tier3/main.tf

* Update Terraform to version 1.0.4
* Update azurerm to version 2.70.0
* Update az cli to version 2.27.0
Pinned terraform version to 1.0.4 in main.tf files
This configuration was tested in Azure Commercial and Government (usgovvirginia)
NA

Update Terraform to version 1.0.4

---

src/docs/terraform/deployment.md

* add terraform cli docs
* specify terraform version
The issue this PR will close: #_[issue number]_

Provide docs on deployment using native terraform CLI commands (#377)

---

src/bicep/marketplace/README.md
src/bicep/marketplace/createUiDefinition.json
src/bicep/marketplace/mainTemplate.json
src/bicep/mlz.bicep
src/bicep/mlz.json
src/bicep/ui/README.md
src/bicep/ui/mlz-portal.json

Put together UI template for visual customer setup.  Bladed UI uses default output from a bicep compile. This is an initial commit and can be heavily extended with constraints and other options.
Test URL's are at:
https://github.com/Azure/missionlz/tree/breestryker/bicep_ui/src/bicep/ui
Will need to be updated to bicep branch post testing.   (Eventually to main when Bicep goes to main)
The issue this PR will close: #351 

add an initial form user interface

---

src/bicep/marketplace/README.md
src/bicep/marketplace/createUiDefinition.json
src/bicep/marketplace/mainTemplate.json
src/bicep/mlz.bicep
src/bicep/mlz.json
src/bicep/modules/resourceGroup.bicep
src/bicep/ui/README.md
src/bicep/ui/mlz-portal.json
src/docs/terraform/deployment.md

The issue this PR will close: #_[issue number]_

Merge bicep to working

---

.devcontainer/Dockerfile
src/terraform/mlz/main.tf
src/terraform/tier3/main.tf

Update Terraform to version 1.0.6
Update azurerm to version 2.76.0
Update az cli to version 2.28.0
Update tflint to version 0.32.1
Update tflint azurerm rules to version 0.13.1
This configuration was tested in Azure Commercial and Government (usgovvirginia)
NA

Update Terraform to version 1.0.6

---

README.md

Modified the README.md file to reflect that we are not using Liux Shell scripts and reference the fact that we are using Bicep
The issue this PR will close: #435
* [*] All acceptance criteria in the backlog item are met
* [*] The documentation is updated to cover any new or changed features
* [*] Manual tests have passed
* [*] Relevant issues are linked to this PR

Corrected text in README.md

---

src/bicep/examples/remoteAccess/README.md
src/bicep/examples/remoteAccess/main.bicep
src/bicep/examples/remoteAccess/main.json

Since the Remote Access example was create the `src/bicep/modules/remoteAccess` module has since been updated to include a Log Analytics Workspace for logging. This change includes that parameter and updates the example docs.
The issue this PR will close: #471 

update the remote access example to include a log analytics workspace

---

.devcontainer/Dockerfile
.github/workflows/validate-terraform.yml
src/terraform/mlz/main.tf
src/terraform/tier3/main.tf

* Update Terraform to version 1.0.10
* Update azurerm to version 2.83.0
* Update az cli to version 2.29.2
* Update tflint to version 0.33.0
* Update tflint azurerm rules to version 0.13.2
This configuration was tested in Azure Commercial and Government (usgovvirginia)
NA

Updating Tools

---

.azure-devops/cred-poli-scan.yml
.azure-devops/nightlybuild/mlz-bicep-azurecloud-pipelines.yml
.azure-devops/nightlybuild/mlz-bicep-azuregov-pipelines.yml
.azure-devops/nightlybuild/mlz-tf-azurecloud-pipelines.yml
.azure-devops/nightlybuild/mlz-tf-azuregov-pipelines.yml
.azure-devops/prbuild/mlz-pr-bicep-azurecloud-pipelines.yml
.azure-devops/prbuild/mlz-pr-bicep-azuregov-pipelines.yml
.azure-devops/prbuild/mlz-pr-tf-azurecloud-pipelines.yml
.azure-devops/prbuild/mlz-pr-tf-azuregov-pipelines.yml

- Removes the CI trigger for PR pipelines and filters them to just `/main`
- Removes the dead branch `mlz-azure-pipelines` from the nightly schedule
The issue this PR will close: #49 #94 

update PR builds and scheduled deployment triggers

---

.azure-devops/nightlybuild/mlz-tf-azuregov-pipelines.yml

Update mlz-tf-azuregov-pipelines.yml for Azure Pipelines

---

README.md

Updated the links in the Getting Started section of the root `README.md` file.
The issue this PR will close: None

Link update for main README

---

CONTRIBUTING.md

Added a "collaborate" section to the getting started guide. It has guidance on the importance of collaboration and when to ask for help, as well as specific advice on what to do when stuck on an engineering problem.
The issue this PR will close: N/A

Add collaboration section to contribution guide

---

src/bicep/core/README.md
src/bicep/modules/README.md

This will correct some relative links that are incorrectly pointing to the docs folder
The issue this PR will close: #711

Fix broken relative links

---

src/bicep/mlz.bicep
src/bicep/mlz.json

_one line change, to enable Azure Defender for the Cloud to deploy to all spoke resource groups_
The issue this PR will close: #719 

Fix spoke deployment of Defender

---

src/bicep/examples/iaas-activedirectory-domaincontrollers/README.md

Changed -TemplateFile location for deployment from .\forwarderVm.bicep to .\activeDirectoryDomainController.bicep
Changed -TemplateFile location for deployment from .\forwarderVm.bicep to .\activeDirectoryDomainController.bicep
The issue this PR will close: #[issue number]

Update README.md for IAAS-ActiveDirectory-Example

---

README.md

Removed ADO pipelines
The issue this PR will close: #783

Removed ADO pipelines

---

src/bicep/core/hub-customer-managed-keys.bicep
src/bicep/mlz.bicep
src/bicep/mlz.json

The DES and Key Vault can't be in a different sub and location than the VM being encrypted.

Moved CMK resources to HUB

---

docs/esri.md

Corrected spelling errors and broken hyperlinks on ESRI ReadMe

854 esri documentation updates

---

src/bicep/add-ons/esri-enterprise/README.md

updated pre-reqs and ArcGIS README.MD
The issue this PR will close: #935 

935 update esri readmemd

---

src/bicep/form/mlz.portal.json

Added warning banner for Azure Policy

---

src/bicep/add-ons/esri-enterprise/modules/managementVirtualMachine.bicep
src/bicep/add-ons/esri-enterprise/solution.bicep
src/bicep/add-ons/esri-enterprise/solution.json

update container and pip dns name
The issue this PR will close: #963

add pip unique dns name and update container for artifacts in mgmt vm

---

src/bicep/add-ons/imaging/uiDefinition.json

update default zip file name in UI for ArcGISPro.zip 
The issue this PR will close: #991 

update ArcGISpro.zip UI

---

src/bicep/add-ons/azureVirtualDesktop/modules/logic.bicep
src/bicep/add-ons/azureVirtualDesktop/solution.bicep
src/bicep/add-ons/azureVirtualDesktop/solution.json

See details in linked issue
The issue this PR will close: #901 

Fixed vm name prefix in vm template

---

docs/deployment-guides/templatespec.md

Edited URL paths for json file links
The issue this PR will close: #1103

updated path

---

docs/deployment-guides/templatespec.md

Fixed URL (../../src/bicep/form/mlz.portal.json)
The issue this PR will close: #1105

fixed last broken URL

---

src/bicep/mlz.json
src/bicep/modules/linux-virtual-machine.bicep

added enableAutomaticUpgrade back into code since issues was OBE.
The issue this PR will close: #1116 

added enableAutomaticUpgrade back into code since issues was OBE.

---

src/bicep/add-ons/imaging/uiDefinition.json

Adjusted Custom UI for Zero Trust Imaging solution (Add-on)
Corrected the following:
1. Noted field for files did not have the right validation for file extensions and adjusted syntax as it did not match for VDOT
2. Added notes to Networking regarding what is being deployed and prerequisites needed.
3. In Compliance section, fixed section to select Log Analytics.
The issue this PR will close: #1120 

JCore-ZeroTrustImg-bug#1120

---

docs/deployment-guides/command-line-tools.md
src/bicep/add-ons/azure-virtual-desktop/modules/fslogix/fslogix.bicep
src/bicep/add-ons/azure-virtual-desktop/modules/sessionHosts/virtualMachines.bicep
src/bicep/add-ons/azure-virtual-desktop/solution.bicep
src/bicep/add-ons/azure-virtual-desktop/solution.json
src/bicep/add-ons/azure-virtual-desktop/uiDefinition.json
src/bicep/add-ons/imaging/solution.json
src/bicep/add-ons/tier3/modules/storage.bicep
src/bicep/add-ons/tier3/solution.bicep
src/bicep/add-ons/tier3/solution.json

- Fixed the conditions for Intune enrollment and FSLogix storage
- Fixed the missing params for tier 3 storage
The issue this PR will close: #1122 

Fixed conditions in AVD Add-On & missing params in Tier3 for storage

---

src/bicep/add-ons/azure-virtual-desktop/modules/sessionHosts/sessionHosts.bicep
src/bicep/add-ons/azure-virtual-desktop/modules/sessionHosts/virtualMachines.bicep
src/bicep/add-ons/azure-virtual-desktop/solution.bicep
src/bicep/add-ons/azure-virtual-desktop/solution.json

- Updated the configuration file to latest version
- Added a param for the configuration file name to support different files for different clouds
- Fixed a bug with Entra joining the virtual machines
The issue this PR will close: #1091 

AVD Add-On: Updated configuration zip file & fixed Entra join bug

---

src/bicep/add-ons/azure-virtual-desktop/solution.json
src/bicep/add-ons/esri-enterprise/solution.json
src/bicep/add-ons/imaging/solution.json
src/bicep/add-ons/tier3/solution.json
src/bicep/mlz.json
src/bicep/modules/key-vault.bicep

Changed the key type from RSA to RSA HSM.
The issue this PR will close: #1172 
Testing validation:

MLZ & Add-Ons: Fixed Key Type on Key Vault Keys

---

src/bicep/add-ons/azure-virtual-desktop/modules/sessionHosts/virtualMachines.bicep
src/bicep/add-ons/azure-virtual-desktop/solution.bicep
src/bicep/add-ons/azure-virtual-desktop/solution.json

- Added the GPU driver setting required for NVv3 VM sizes
- Updated the configuration file version for the AVD agents
The issue this PR will close: #1178 

AVD Add-On: Added GPU Driver Condition & Updated AVD Agent Configuration File Version 

---

src/bicep/data/locations.json
src/bicep/mlz.json

Updated locations

---

src/add-ons/README.md
src/add-ons/imaging/modules/baseline.bicep
src/add-ons/imaging/modules/baseline.json
src/add-ons/imaging/modules/build-automation.bicep
src/add-ons/imaging/modules/image-build.bicep
src/add-ons/imaging/modules/image-build.json
src/add-ons/imaging/modules/restart-virtual-machine.bicep
src/add-ons/imaging/scripts/Restart-AzureVirtualMachine.ps1
src/add-ons/imaging/solution.bicep
src/add-ons/imaging/solution.json
src/add-ons/imaging/uiDefinition.json

- Fixed the log analytics workspace used for monitoring the tier3 resources and build automation
- Fixed the scope on the imaging resources so they are created in the proper resource group
- Fixed the firewall rules so the mgmt, update, and KMS traffic are allowed
- Updated the Add-Ons MD file so that all current add-ons are listed
This PR will close: #1223 #1224 #1225

Fixed Imaging Add-On: LAW inputs & refs, scope for imaging resources, & FW rules

---

src/add-ons/README.md

Fixed table formatting for the add-ons table in the readme.md file

Fixed table formatting for add-ons
